# Generated by Django 3.2.9 on 2021-12-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='body3',
        ),
    ]
