# Generated by Django 3.2 on 2021-11-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='test',
        ),
    ]
