# Generated by Django 3.2.9 on 2021-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenge', '0002_auto_20211214_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
