# Generated by Django 3.2.9 on 2021-12-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenge', '0003_submission_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='correct',
            field=models.BooleanField(blank=True),
        ),
    ]
